### PR TITLE
Upgraded to JTS 1.15.0

### PR DESCRIPTION
**Pull request by jnh5y**
* Did a 'find and replace' on com.vividsolutions for org.locationtech with

git grep -l com.vividsolutions | grep pom.xml | xargs sed -i "s/com.vividsolutions/org.locationtech.jts/g"
git grep -l com.vividsolutions | xargs sed -i "s/com.vividsolutions/org.locationtech/g"

* Pulled out the JTS version as a Maven property.

* Disabled the 'app' build since the henplus artifacts are not available.

Signed-off-by: Jim Hughes <jnh5y@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
Jody and I are still testing these PRs.  They may not be ready to merge yet.

**Comment by jodygarnett** [comment]
Building master did not work ...

```
[INFO] GeoDB 0-SNAPSHOT ................................... SUCCESS [  0.548 s]
[INFO] GeoDB Core ......................................... SUCCESS [  0.024 s]
[INFO] GeoDB App 0-SNAPSHOT ............................... FAILURE [  0.007 s]
```

The GeoDB App fails as `net.sourceforge:henplus:jar:0.9.8 ` is not available?

This branch builds with dependencies - but skips the app:

````
[INFO] org.opengeo:geodb:jar:0-SNAPSHOT
[INFO] +- com.h2database:h2:jar:1.1.118:compile
[INFO] +- org.locationtech.jts:jts-core:jar:1.15.0:compile
[INFO] +- net.sourceforge.hatbox:hatbox:jar:1.0.b10:compile
[INFO] \- junit:junit:jar:4.7:test
````

Okay HenPlus moved here https://github.com/neurolabs/henplus, with no sign of release but has had recent (within a year) development so it is not dead.

**Comment by jodygarnett** [comment]
This is ready to go! @jdeolive can you merge this and I will publish jar to repo.boundlessgeo.com

(Although your credentials should still work as a community member)

**Comment by jdeolive** [comment]
THanks guys!

**Comment by jodygarnett** [comment]
Nice, so can you push up a tag for 0.9? Not sure I can do a PR for a tag...

**Pull request merged**
